# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
